{
    'name': 'Odoo K8s SaaS — Subscription Bridge',
    'version': '18.0.1.1.0',
    'summary': 'Links subscription_oca lifecycle to SaaS instance provisioning',
    'category': 'Technical',
    'author': 'AEI Software',
    'license': 'LGPL-3',
    'depends': ['odoo_k8s_saas', 'subscription_oca', 'portal', 'website_sale'],
    'data': [
        'security/ir.model.access.csv',
        'security/ir_rules.xml',
        'data/subscription_templates.xml',
        'data/ir_cron.xml',
        'data/website_checkout_config.xml',
        'views/saas_instance_views.xml',
        'views/sale_subscription_views.xml',
        'views/subscription_template_views.xml',
        'views/subscription_portal_templates.xml',
        'views/website_assets.xml',
    ],
    'installable': True,
    'auto_install': True,
    'application': False,
}
